---
title: "Ten Simple Rules: Draft Rules"
author: "Lukas M. Weber, Wouter Saelens, Robrecht Cannoodt, Charlotte Soneson, Yvan Saeys, Mark D. Robinson"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---


# Ten Simple Rules for a Method Benchmarking or Comparison

Draft rules for pre-submission inquiry letter; merged version of rules based on initial drafts from both labs. With notes explaining how each merged rule relates to the initial proposed rules from the drafts from each lab.


## Rules:


#### Rule 1: Define the purpose and scope of your benchmarking or comparison

- Rule 1 from Saeys draft
- Rule 1 from Robinson draft
- also covers part of Rule 2 from Saeys draft


#### Rule 2: Ensure that you have included all relevant methods

- Rule 3 from Saeys draft
- also covers part of Rule 2 from Saeys draft


#### Rule 3: Select (or design) a variety of representative benchmark datasets

- Rule 4 from Saeys draft
- Rules 2 and 3 (combined) from Robinson draft
- also covers part of Rule 6 from Saeys draft


#### Rule 4: Evaluate methods according to statistical performance metrics

- Rule 4 from Robinson draft
- first part of Rule 5 from Saeys draft
- also parts of Rule 6 from Saeys draft


#### Rule 5: Compare runtimes, computational requirements, user-friendliness, and documentation

- second part of Rule 5 from Saeys draft
- Rule 7 from Robinson draft


#### Rule 6: Record all parameter settings, as well as environment or session information

- Rule 6 from Robinson draft
- part of Rule 8 from Saeys draft


#### Rule 7: Consider your audience: interpret results and provide conclusions or guidelines from both user and method developer perspectives

- Rule 7 from Saeys draft
- part of Rule 5 from Robinson draft
- part of Rule 8 from Robinson draft
- Rule 10 from Saeys draft


#### Rule 8: Publish your results in an accessible format

- rest of Rule 8 from Robinson draft
- part of Rule 10 from Saeys draft


#### Rule 9: Design the benchmarking to allow future extensions to include new methods or new datasets

- Rule 9 from Saeys draft
- Rule 9 from Robinson draft


#### Rule 10: Follow reproducible research best practices by making all code and data available in public repositories

- Rule 10 from Robinson draft
- Rule 8 from Saeys draft



